version: '3.6'

services:
  pgdb:
    restart: always
    container_name: pgdb
    image: postgres:10.0
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=qweqwe123
      - TZ=Asia/Shanghai
      - PGTZ=Asia/Shanghai
    volumes:
      - ./data:/var/lib/postgresql/data:z
      - /etc/localtime:/etc/localtime:ro

networks:
  default:
    external:
      name: prod

