version: "2.4"

services:
    influxdb:
        image: influxdb
        volumes:
            - ./influxdb/var/lib:/var/lib/influxdb
            - ./influxdb/etc:/etc/influxdb
        environment:
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=admin
        ports:
            - 8083:8083
            - 8086:8086
        privileged: true

    grafana:
        image: grafana/grafana
        volumes:
            - ./grafana/etc:/etc/grafana
            - ./grafana/var/lib:/var/lib/grafana
            - ./grafana/var/lib/plugins:/var/lib/grafana/plugins
            - ./grafana/var/lib/provisioning:/var/lib/grafana/provisioning
            - ./grafana/var/log:/var/log/grafana
        links:
            - influxdb:influxdb
        environment:
            - GF_INSTALL_PLUGINS=grafana-clock-panel
        ports:
            - 3030:3000
        depends_on:
            - influxdb
        privileged: true
