version: "3.6"

services:
    influxdb:
        image: influxdb
        container_name: ${CONTAINER_1}
        volumes:
            - ./influxdb/var/lib:/var/lib/influxdb
            - ./influxdb/etc:/etc/influxdb
        environment:
            - INFLUXDB_ADMIN_USER=${INFLUX_ADMIN_USERNAME}
            - INFLUXDB_ADMIN_PASSWORD=${INFLUX_ADMIN_PASSWORD}
        ports:
            - 8086:8086
        privileged: true

    grafana:
        image: grafana/grafana
        container_name: ${CONTAINER_2}
        volumes:
            - ./grafana/etc:/etc/grafana
            - ./grafana/var/lib:/var/lib/grafana
        links:
            - influxdb:influxdb
        ports:
            - 3030:3000
        depends_on:
            - influxdb
        privileged: true



