version: '3'
services:
  nginx:
    restart: always
    container_name: nginx-prod
    image: nginx:1.17.6
    ports:
      - "80:80"
    volumes:
      - ./data:/etc/nginx

networks:
  default:
    external:
      name: prod
