version: "3.6"

services:
  mysql:
    restart: always
    container_name: ${CONTAINER_NAME}
    image: mysql:${VERSION}
    ports:
      - ${PORT}:3306
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_ROOT_PASSWORD: ${PASSWORD}

    volumes:
      - ./data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro

networks:
  default:
    external:
      name: ${NETWORK_NAME}
